### PR TITLE
Commiting Test2 to anahuX

### PR DESCRIPTION
**Pull request by Vidshalgit12**
Hi 
I have created the Test2 file ,please review and approve

### CODE REVIEW

**Comment by Vidshalgit12** [comment]
Hi X
your code looks good ,please add one more check .
Regards
V

**Comment by AnahuGit** [comment]
Hi V
I have added additional Checks ,please approve

**Comment by Vidshalgit12** [comment]
Hi X
Now it is good ,Now merge it .

**Review by AnahuGit — COMMENTED** [review]
Adding now

**Pull request merged**
